services:
  - type: web
    name: youtube-downloader
    env: docker
    plan: free
    dockerCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: COOKIES_DATA
        sync: false  # Optional; set manually in Render dashboard if needed
