services:
  - type: web
    name: youtube-downloader
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12  # Specify a full version (major.minor.patch)
      - key: COOKIES_DATA
        sync: false  # Optional; set manually in Render dashboard if needed
